name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  build-docker:
    timeout-minutes: 8
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Start containers using docker compose
        run: |
          echo ${{ secrets.bot_token }} > .env
          docker-compose up --build -d
      - name: Stop containers
        if: always()
        run: docker-compose down --rmi all
