name: Build

on:
  push:
    branches:
      - rewrite
  pull_request:
    branches:
      - rewrite
    types: [closed]

jobs:
  build-docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build using docker compose
        run: |
          pwd
          sudo docker-compose up --build
